### ISSUE TITLE
Available for sylius 1.12

### ISSUE THREAD

**Issue by GediminasLaurinaitis** [monsieurbiz/SyliusMenuPlugin#26]
Hello,

Do you plan to add compatibility with Sylius 1.12?

**Comment by delyriand** [comment]
Hi @GediminasLaurinaitis 

I have completed your PR #28 and the tag [v1.1.0](https://github.com/monsieurbiz/SyliusMenuPlugin/releases/tag/v1.1.0) is compatible with sylius 1.12
